# Generated by Django 4.2 on 2023-08-15 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0002_authsession_fcm_player_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authsession",
            name="expired_at",
        ),
    ]
