# Generated by Django 4.2 on 2023-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0003_remove_authsession_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authsession",
            name="device_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
