# Generated by Django 4.2 on 2023-07-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("otp_type", models.SmallIntegerField(choices=[(1, 1), (2, 2)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("expried_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                (
                    "user_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Học sinh"),
                            (1, "Phụ huynh"),
                            (2, "Sinh viên"),
                            (3, "Giáo viên"),
                            (4, "Thí sinh tự do"),
                            (5, "Khác"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "sex",
                    models.SmallIntegerField(
                        choices=[(0, "Nam"), (1, "Nữ"), (2, "Khác")], default=2
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=11, null=True)),
                ("birth_day", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("avatar_url", models.TextField(null=True)),
                ("address", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_type",
                    models.SmallIntegerField(
                        auto_created=True,
                        choices=[(1, "Email"), (2, "Google"), (3, "Microsoft")],
                        default=1,
                    ),
                ),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=256, null=True)),
                ("auth_id", models.CharField(max_length=128, null=True, unique=True)),
                ("last_login", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "auth_otp",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="FK_AUTH_OTP",
                        to="users.otp",
                    ),
                ),
                (
                    "password_otp",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="FK_PASSWORD_OTP",
                        to="users.otp",
                    ),
                ),
                (
                    "user_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="FK_USER_INFO",
                        to="users.userinfo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
