# Generated by Django 4.2 on 2023-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
